In [1]:
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from collections import Counter
import pandas as pd
import json

In [2]:
# Load the data
file_path = '/kaggle/input/synthetic-student-profiles-dataset/student_profiles.jsonl'
data = []
with open(file_path, 'r') as file:
    for line in file:
        data.append(json.loads(line))
df = pd.DataFrame(data)

In [3]:
df

Name  Age     Sex                    Major       Year  \
0           Thomas Ibarra   24    Male             Biochemistry     Senior   
1      Timothy Wilson PhD   23    Male  Business Administration     Senior   
2             Nancy Brown   23  Female              Archaeology  Sophomore   
3             Donna Reyes   19  Female   Mechanical Engineering     Senior   
4           Mary Gonzales   24  Female                Sociology   Freshman   
...                   ...  ...     ...                      ...        ...   
23231      Caitlin Orozco   19  Female               Journalism     Junior   
23232      Aaron Robinson   23    Male              Meteorology   Freshman   
23233  Donald Hawkins DDS   21    Male      Nuclear Engineering  Sophomore   
23234       David Shelton   22    Male              Mathematics     Junior   
23235         Erin Massey   24  Female       Veterinary Science     Senior   

        GPA                            Hobbies Country State/Province  \
0      2.83        [table tennis, photography]     USA  Massachusetts   
1      2.37        [snowboarding, ice skating]  Canada        Ontario   
2      3.44              [dancing, bouldering]     USA           Iowa   
3      2.35            [astronomy, geocaching]  Canada        Ontario   
4      2.42    [puzzle solving, bird watching]  Canada        Ontario   
...     ...                                ...     ...            ...   
23231  3.95  [horseback riding, tarot reading]     USA        Georgia   
23232  3.16                [philately, gaming]     USA      Wisconsin   
23233  2.34           [stone carving, origami]  Canada        Ontario   
23234  2.37           [digital art, astrology]     USA        Alabama   
23235  4.15          [wine tasting, dodgeball]     USA       Missouri   

                        Unique Quality  \
0             Wildlife conservationist   
1                    Virtuoso musician   
2                  Graphic design guru   
3               Kite flying enthusiast   
4                     A natural leader   
...                                ...   
23231           Tea culture enthusiast   
23232  Innovative and forward-thinking   
23233         Superb analytical skills   
23234                Karate black belt   
23235         Compassionate and caring   

                                                   Story  
0      Thomas Ibarra was a senior at the prestigious ...  
1      Timothy Wilson was a senior at a prestigious u...  
2      Nancy Brown was a sophomore at Iowa State Univ...  
3      Donna Reyes was a senior at her university in ...  
4      Mary Gonzales was a freshman at Ontario Univer...  
...                                                  ...  
23231  Caitlin Orozco was a junior at a prestigious u...  
23232  Aaron Robinson was a freshman at the Universit...  
23233  Donald Hawkins DDS was a sophomore at the pres...  
23234  David Shelton was a junior at the University o...  
23235  Erin Massey had always known she wanted to be ...  

[23236 rows x 11 columns]

In [7]:
import pandas as pd
import json
import random
import string
import numpy as np

In [8]:
def generate_unique_id(length=7):
    characters = string.ascii_lowercase + ''.join(map(str, range(1, 10)))
    return ''.join(random.choices(characters, k=length))
unique_ids = set()
for _ in range(len(df)):
  while True:
    new_id = generate_unique_id()
    if new_id not in unique_ids:
      unique_ids.add(new_id)
      break
df['unique_id'] = list(unique_ids)



In [9]:
df

Name  Age     Sex                    Major       Year  \
0           Thomas Ibarra   24    Male             Biochemistry     Senior   
1      Timothy Wilson PhD   23    Male  Business Administration     Senior   
2             Nancy Brown   23  Female              Archaeology  Sophomore   
3             Donna Reyes   19  Female   Mechanical Engineering     Senior   
4           Mary Gonzales   24  Female                Sociology   Freshman   
...                   ...  ...     ...                      ...        ...   
23231      Caitlin Orozco   19  Female               Journalism     Junior   
23232      Aaron Robinson   23    Male              Meteorology   Freshman   
23233  Donald Hawkins DDS   21    Male      Nuclear Engineering  Sophomore   
23234       David Shelton   22    Male              Mathematics     Junior   
23235         Erin Massey   24  Female       Veterinary Science     Senior   

        GPA                            Hobbies Country State/Province  \
0      2.83        [table tennis, photography]     USA  Massachusetts   
1      2.37        [snowboarding, ice skating]  Canada        Ontario   
2      3.44              [dancing, bouldering]     USA           Iowa   
3      2.35            [astronomy, geocaching]  Canada        Ontario   
4      2.42    [puzzle solving, bird watching]  Canada        Ontario   
...     ...                                ...     ...            ...   
23231  3.95  [horseback riding, tarot reading]     USA        Georgia   
23232  3.16                [philately, gaming]     USA      Wisconsin   
23233  2.34           [stone carving, origami]  Canada        Ontario   
23234  2.37           [digital art, astrology]     USA        Alabama   
23235  4.15          [wine tasting, dodgeball]     USA       Missouri   

                        Unique Quality  \
0             Wildlife conservationist   
1                    Virtuoso musician   
2                  Graphic design guru   
3               Kite flying enthusiast   
4                     A natural leader   
...                                ...   
23231           Tea culture enthusiast   
23232  Innovative and forward-thinking   
23233         Superb analytical skills   
23234                Karate black belt   
23235         Compassionate and caring   

                                                   Story unique_id  
0      Thomas Ibarra was a senior at the prestigious ...   3ihpkgv  
1      Timothy Wilson was a senior at a prestigious u...   l81xra4  
2      Nancy Brown was a sophomore at Iowa State Univ...   87l59ip  
3      Donna Reyes was a senior at her university in ...   kug1sjf  
4      Mary Gonzales was a freshman at Ontario Univer...   7gmk461  
...                                                  ...       ...  
23231  Caitlin Orozco was a junior at a prestigious u...   unbftxn  
23232  Aaron Robinson was a freshman at the Universit...   hqaqha7  
23233  Donald Hawkins DDS was a sophomore at the pres...   xznqcjt  
23234  David Shelton was a junior at the University o...   5i8l8gn  
23235  Erin Massey had always known she wanted to be ...   3i7xv8y  

[23236 rows x 12 columns]

In [10]:
df.to_csv('students_data2.csv', index=False)

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
vectorizer = TfidfVectorizer()

In [13]:
X = vectorizer.fit_transform(df['Story'])

In [14]:
cosine_sim = np.dot(X, X.T).toarray()

In [15]:
cosine_sim

array([[1.        , 0.25288416, 0.12572706, ..., 0.25556456, 0.32832757,
        0.15126138],
       [0.25288416, 1.        , 0.10069615, ..., 0.23001306, 0.31750602,
        0.123601  ],
       [0.12572706, 0.10069615, 1.        , ..., 0.13182023, 0.1300381 ,
        0.32631529],
       ...,
       [0.25556456, 0.23001306, 0.13182023, ..., 1.        , 0.31199499,
        0.12235654],
       [0.32832757, 0.31750602, 0.1300381 , ..., 0.31199499, 1.        ,
        0.15153618],
       [0.15126138, 0.123601  , 0.32631529, ..., 0.12235654, 0.15153618,
        1.        ]])

In [ ]:
similarity_matrix_df = pd.DataFrame(cosine_sim)
similarity_matrix_df.to_csv('similarity.csv', index=False)

In [17]:
from IPython.display import FileLink
FileLink(r'/kaggle/working/similarity.csv')

/kaggle/working/similarity.csv

In [18]:
df1 = pd.read_csv(r'/kaggle/working/similarity.csv')

In [19]:
df1

0         1         2         3         4         5         6  \
0      1.000000  0.252884  0.125727  0.106149  0.118769  0.273078  0.131156   
1      0.252884  1.000000  0.100696  0.091246  0.101050  0.291825  0.109688   
2      0.125727  0.100696  1.000000  0.333598  0.310119  0.140469  0.312705   
3      0.106149  0.091246  0.333598  1.000000  0.406759  0.116336  0.382273   
4      0.118769  0.101050  0.310119  0.406759  1.000000  0.114390  0.365155   
...         ...       ...       ...       ...       ...       ...       ...   
23231  0.118836  0.087903  0.237897  0.275022  0.248235  0.123145  0.280136   
23232  0.271019  0.249448  0.123314  0.106987  0.126220  0.288811  0.127469   
23233  0.255565  0.230013  0.131820  0.111315  0.107613  0.260406  0.144472   
23234  0.328328  0.317506  0.130038  0.121279  0.126908  0.331284  0.141470   
23235  0.151261  0.123601  0.326315  0.423328  0.385284  0.139106  0.385012   

              7         8         9  ...     23226     23227     23228  \
0      0.120037  0.145238  0.268090  ...  0.128818  0.301139  0.112375   
1      0.127069  0.106637  0.256787  ...  0.110681  0.301254  0.096316   
2      0.317619  0.282023  0.122870  ...  0.329390  0.146734  0.265133   
3      0.403040  0.343830  0.103208  ...  0.425646  0.121972  0.328825   
4      0.394836  0.334581  0.112549  ...  0.414810  0.116551  0.309761   
...         ...       ...       ...  ...       ...       ...       ...   
23231  0.255232  0.245608  0.108426  ...  0.277291  0.137217  0.228974   
23232  0.119346  0.123088  0.259330  ...  0.129006  0.293359  0.107938   
23233  0.118429  0.121284  0.259305  ...  0.139309  0.283148  0.111612   
23234  0.131215  0.161497  0.323044  ...  0.140367  0.375577  0.123503   
23235  0.381649  0.368474  0.130517  ...  0.406345  0.143226  0.327651   

          23229     23230     23231     23232     23233     23234     23235  
0      0.113617  0.132958  0.118836  0.271019  0.255565  0.328328  0.151261  
1      0.093743  0.105551  0.087903  0.249448  0.230013  0.317506  0.123601  
2      0.275626  0.258200  0.237897  0.123314  0.131820  0.130038  0.326315  
3      0.343650  0.311360  0.275022  0.106987  0.111315  0.121279  0.423328  
4      0.321284  0.290754  0.248235  0.126220  0.107613  0.126908  0.385284  
...         ...       ...       ...       ...       ...       ...       ...  
23231  0.243983  0.226324  1.000000  0.102958  0.106282  0.110948  0.289177  
23232  0.116560  0.115931  0.102958  1.000000  0.261760  0.337681  0.126507  
23233  0.106472  0.140383  0.106282  0.261760  1.000000  0.311995  0.122357  
23234  0.120802  0.132068  0.110948  0.337681  0.311995  1.000000  0.151536  
23235  0.343749  0.319700  0.289177  0.126507  0.122357  0.151536  1.000000  

[23236 rows x 23236 columns]

In [20]:
cosine_sim.shape

(23236, 23236)

In [43]:
top_11_indices = []

# Iterate over each row index in the cosine similarity matrix
for idx in range(cosine_sim.shape[0]):
    # Get the current row
    row = cosine_sim[idx, :]
    # Sort the indices based on the cosine similarity scores in descending order
    sorted_indices = np.argsort(row)[::-1]
    # Exclude the current student's own index (cosine similarity with itself will always be 1)
    sorted_indices = sorted_indices[sorted_indices != idx]
    # Take the top 11 indices
    top_11 = sorted_indices[:11]
    # Store the top 11 indices in the list
    top_11_indices.append(top_11)

In [47]:
top_11_indices

[array([ 5032,  4948,  5168,  1350,  8929, 21715, 20527,  1088,  8081,
         8099, 22928]),
 array([ 4834, 19037, 11546, 13740, 21554, 23207,  1428,  3293,  5593,
          492,  4261]),
 array([ 3953, 16796,  2937,  7012, 16621, 14423,   942, 21632, 19404,
        16699, 19801]),
 array([16154,    12,  3543, 21127, 15893, 17613,   225, 18014, 11651,
         4482,  5059]),
 array([12430,  6577,  6065, 20141, 21662,  7308,  6878, 10297,  8100,
        22393, 21764]),
 array([ 5548, 21495, 15102,  9169, 17685, 10623,  4980,  6839,  4138,
        13726,  4624]),
 array([ 3358,   887,  3745, 14156,  9930, 12807, 14594, 21674,  9738,
           39, 15620]),
 array([16545,  5184, 14321, 19632, 22587,  3896, 22400, 17242,  7046,
        15519,  5311]),
 array([10931, 22312, 12119,  1216,  5996,  2602, 17193, 12928, 12405,
        16041, 18125]),
 array([ 5123, 14660, 13446,  7710, 17122, 22736, 13850,  3327, 22943,
         9865, 12005]),
 array([12109, 10019, 13833, 22010, 17598,  2505, 

In [49]:
df_top_11_indices = pd.DataFrame(top_11_indices)

In [52]:
df_top_11_indices.to_csv('recomendation_student.csv', index=False)

NameError: name 'df_subset' is not defined

NameError: name 'top_11_indices_sorted' is not defined